language: python
python:
- '2.7'
install:
- pip install coveralls
- python setup.py install
script:
- python setup.py test
after_success:
- coveralls
deploy:
  provider: heroku
  api_key:
    secure: RSCQarY7wWFpaR+slYn8NUkhYO2p0T7+95r4C+lTZ0SG1ogcLYmjw4/GmrS8k8mdJ+jUspc5G2v0YrikWPeDdxV5bvRLkEoTZMkaSomAgRjB3tHf/JpfJ6IrJrm8sVPPWwV1QMYzC+KJ33DAw6ZgwAW6rqqycujsKaLCTKv9ITgAWcvxWzEYuesoMSryelV11pR+Vgm8iBuJD+R3bmbZcFnd2Msk+R9GaanvJ/Umr8GLviMS64CshCRx8yV3ORfHXDIsLndJvxCOcW/USg1wYbp6crZxTuGxnnpo2pvo5BFlIEEbiqLvVADWjK+p8cwysyRVYFntJfkJ4/yVNPuOmJcsOKBJ5an86HODavAcBUR00sRwbHqGi+IxnHVUHj6lVbOBjDm+EmmZAQ30/rac4RLa8i9V4a9mL7OAp2W2eP/a+06/2SrO4JMlaJjF/SHco54NepdZViW4iBeCdpXhdDjvT4shSrQ0etW49U3hyD2zvHjXjSR8L0K8F5RZuVbd5aPpsTGIdDuagdh/jTxpYwM7Wd9LjDIz8RUzLnjEYxqo+p2XZ9VDtler9+RqUR7Dp22VZnjZ0UmLP7AuYRBJCPLEoalukQt5V4hRhHyUpdmvyqWmyYRr47sS3sW+Pg83dXojjcpTxFdWWaHLhsNMGKZOOz8udLx5bNt7asCZn98=
  app: bartrackr
  on:
    repo: bencarothers/trackr
