language: python
python:
- '2.7'
install:
- pip install coveralls
- python setup.py install
script:
- python setup.py test
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: McX7KGvv0En+dUaiVI5m2UfFEb8RUaKNvwHu4hgJoOVGV+ZOyd0n/gQFs6VddvSpNKR2MPQLWdtHtYtUiTDmrUEseYr54JUcb8CJUmiuRgrWBG2jGDtJ5Ki5EXcb+qdC0Y1366kpyaTzvGovqcVZhkF95sEzevnBrhz5XS582RgEUC8kn6ahkFxnLV8OVUuMos+AhOLHUQkPVSKyIzQBScBXXVo8kl3Q0wuZgH2I4xG0+XpDfYuwvzf7HxVubWmYwMHe2hNnOUKeFP11FGqzX6AuN0Dj7pUB48tMZDY0R+IuZhsXB4SYmQJphwIb1LSeV9olFqxqMv2aUIJc93inX7IgVzw1ue1CJPkPoyXUyqymOFcp0eZxHamZZTgInshXUNMwejJhu/5gcpA5z/lMlm3BFTKXP5U3HvLF88FeR/a+kmWKfWiOrVFoWSoWqgnAwUlUfAkmPAduFBGmElniGSiVqVOPetEiikMrFewOBoR/QNIhxzSVZukM8CXB5xCIwo1MlkhWWb8vkoOyW+MlA+BfEDMQY+2zBg0NnLUMaCr1CWt3aYk9yHHpik0+qxwpdtdOKftXt7FB1e07QJMITmm2tqnj/w3Rb/cXwTf0+722QriP+UGZe3Cdj3ZBLz57Ifp8qUib87TudNYKaapTKDjGphbqwjddlgMwbDW7sJs=
