language: python
python:
- '2.7'
install:
- pip install coveralls
- python setup.py install
script:
- python setup.py test
after_success: coveralls
deploy:
  provider: heroku
  api_key:
    secure: Fnq19Y8MQMhuNnV4scCAsEjnkYTqarl02m4eGod4vC67Z7k3r6p65gA5lhCOXpCLGiwM7FR9sxdSZ1qx7qbyQmxOVOLTknFsNBqqHptjt2TsLUqMr+KC+XONE5nlGe/z1sXvJJMfdx7Zy75klIvd3xHIjH+hj32h09P5KYr/ijKXEaZCrZOJLv17C3vaNvzv6KKfQaYFhB2VdZEGQO+y83JOB2JQ6Q4Co/PHq7NjnU89FMdGpb9iShySRqhz/fm+1w6aETcNha/YcAKzLgyONAr+ia2wt6nVGg0XJdADTBmBUMynGRtLUUO1paQ7HUchv6V+c4a1pRIZ4NW+3x2QCP2yHXajDanI7PlrIQIeVpV3FL7gOC4GALGc5hhYGCCbkhH+cH1mYtJbZJi3jEK1pJDZeQlVkcta1Vuyf4WOhq8rta63VeURegkxq+/MOKcAqEriTRSIG+JT8oGHgSrqvULtkB8ibEnTxgy9wkCQ3Q3w8EnCE6xWPENa7EfHa5jKhCCPVCocH2EufiZCoP8i+2Oqxgkxo8zAY87hr3HeGBdKEy+6ezwhHL8Qhu1YQGDIpgLgGuY9lormLYajr2GcTg4DTqj41eqgnAJLjUhVeeF3AujNIPz1nIdxcERu+2l3Y+Hl9KHQbPejLVfw67eoY0fOcgiiipNUuZrIyNRbu+s=
